version: '3.9'

services:
  db:
    container_name: mysql_db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: projetoWeb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  api:
    container_name: api
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    container_name: web
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
