version: '3.9'

services:
  db:
    container_name: mysql_db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: projetoWeb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - back-db

  api:
    container_name: api
    depends_on:
      - db
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - back-db
      - back-front
    expose:
      - 8000

  web:
    container_name: web
    depends_on:
      - api
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - back-front
    expose:
      - 3000
    tty: true

networks:
  back-db:
    driver: bridge
  back-front:
    driver: bridge